// Pixel-art badges for the in-game UI. Backed by 32×32 PNGs in
// assets/icons/ (generated by scripts/generate-icons.js), shown as
// crisp pixel art via `image-rendering: pixelated`. PNG instead of
// Unicode emoji so the badges render the same on every device — no
// system-font glyph gaps.

const VICTIM_HTML = `<img class="md-icon icon-victim" src="./assets/icons/victim.png" alt="victim" aria-hidden="true" draggable="false" />`;
const KILLER_HTML = `<img class="md-icon icon-killer" src="./assets/icons/killer.png" alt="killer" aria-hidden="true" draggable="false" />`;

export function victimIcon() { return VICTIM_HTML; }
export function killerIcon() { return KILLER_HTML; }

export function badge({ victim = false, killer = false } = {}) {
  if (victim && killer) return VICTIM_HTML + KILLER_HTML;
  if (victim) return VICTIM_HTML;
  if (killer) return KILLER_HTML;
  return '';
}
